config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations', passwords: 'users/passwords' }

  root 'static_pages#home'

  get 'what_is/'  => 'static_pages#what_is'
  get 'faq/'      => 'static_pages#faq'
  get 'contact/'  => 'contacts#new'
  get 'coming_soon/'  => 'static_pages#coming_soon'
  get 'creating_skills_help/'  => 'static_pages#creating_skills_help'

  get 'dashboard/' => 'dashboards#show'

  resources "contacts", only: [:new, :create]

  resources :skills do
    resources :comments
    collection do
      resources :apprenticeships do
        resources :comments

      end
      get 'teaching'
      get 'learning'
      get 'archived'
    end
  end

  resources :paths do

  end

  resources :users do
    collection do
      get 'teaching'
      get 'learning'
    end
  end
  resources :skill_requests do
  end
  resources :confirmations, on: [:apprenticeships,:skill_requests], as: 'accept_date', only:[:new, :update, :delete, :create]
  resources :categories
  resources :locations
  resources :notifications

end

app/models/skill_request.rb
class SkillRequest < ActiveRecord::Base
  include HashModifiers

  include Rails.application.routes.url_helpers

  scope :not_confirmed, ->{ where.not(accepted_status:'confirmed')}
  scope :in_location, ->(ids) { where('location_id in (?)',ids)}
  scope :in_categories,  ->(ids) { joins(:categories).where('categories.id in (?)', ids)}

  validates :title, :subtitle, :full_description,:user_id,:meeting_date_requested,:location_id, :presence => true

  has_many :skill_request_categories, dependent: :destroy
  has_many :categories, through: :skill_request_categories
  belongs_to  :skill_level

  belongs_to :location
  belongs_to :user

  accepts_nested_attributes_for :location

  delegate :city,
           :state,
           :zip,
           to: :location,
           prefix: true

  def to_param
    "#{id} #{title}".parameterize
  end

  def base_uri
    skill_request_path(self)
  end

  def self.search
    not_confirmed.includes(:location,:categories)
  end

  def changed_accepted_status
    {title: "Enrollment in skill has been approved".freeze,
    description:"Congrats! You've been approved to take this skill! Start communicating with your teacher now.".freeze}
  end
end

app/controllers/skill_requests_controller.rb
class SkillRequestsController < ApplicationController

  include SearchHelper
  include DashboardHelper

  before_filter :login_required, only:[:new]

  def index
    @skills  = search_for(SkillRequest, params).paginate(:page => params[:page])
    respond_to do |format|
      format.js { render :partial =>  'refills/cards', :content_type => 'text/html', layout:false }
      format.html
    end
  end

  def show
    @skill_request = SkillRequest.find(params[:id])
  end

  def new
    @categories = Category.order('name')
    @skill_request = SkillRequest.new
    @skill_request.categories.build
    @skill_request.build_location
  end

  def create
    params[:skill_request].merge!({user_id: current_user.id})
    category_ids = params[:skill_request]["category_ids"].split(',')
    params[:skill_request].merge!({category_ids: category_ids})
    @skill_request = SkillRequest.new(skill_request_params)
    @skill_request.location_id = find_location
    if @skill_request.save
      redirect_to dashboard_path
    else
      render 'new'
    end
  end

  def edit
    skill_request = SkillRequest.find(params[:id])
    if current_user == skill_request.user
      @skill_request = skill_request
    else
      redirect_to root_path
    end
  end

  def update
    @skill_request = SkillRequest.find(params['id'])
    params[:skill_request]["category_ids"] ||= []
    category_ids = params[:skill_request]["category_ids"].split(',')
    params[:skill_request].merge!({category_ids: category_ids})
    if @skill_request.update_attributes(skill_request_params)
      @skill_request.location_id = find_location(@skill_request)
      if @skill_request.save
        redirect_to @skill_request
      else
        render 'edit'
      end
    else
      render 'edit'
    end
  end

  def destroy
    skill_request = SkillRequest.find(params[:id])
    skill_request.destroy
    redirect_to dashboard_path
  end

  def check_accepted_status
    skill_request = SkillRequest.find(params[:id])
    skill_request.accepted_status = params["skill_request"]["accepted_status"]
    case skill_request.accepted_status
    when "confirmed"
      unless skill_request.has_apprenticeship?
        skill = Skill.create_skill_from_request({skill_request:skill_request,user:current_user, is_active: true})
        apprenticeship = Apprenticeship.new.create_apprenticeship_from_skill({skill:skill,skill_request:skill_request})
        if apprenticeship.valid? && skill.valid?
          skill_request.has_apprenticeship = true
          skill_request.save
        else
          skill_request.accepted_status = "pending"
          skill_request.save
        end
        current_user_dash_items
        respond_to do |format|
          format.html{redirect_to(dashboard_path)}
          format.js { render :action => 'update_dashboard.js.erb'}
        end
      else
        respond_to do |format|
          format.js { render :action => 'skill-request-confirm-error.js.erb', :locals => {:skill_request => skill_request}}
        end
      end
    end
  end

  private

    def skill_request_params
      params.require(:skill_request).permit(:title,:subtitle,:accepted_status,:meeting_date_requested,:skill_level_id,:full_description,:user_id,:location_id,category_ids:[])
    end

    def find_location(skill_request = SkillRequest.new)
      skill_request.location_id.to_s.blank? ? Location.find_or_create_by(params[:skill_request][:location_attributes].symbolize_keys).id : skill_request.location_id
    end

end

app/helpers/skill_requests_helper.rb
module SkillRequestsHelper

end

app/views/skill_requests/check_accepted_status.js.erb
$(".dashboard").replaceWith("<%= escape_javascript(render :partial => 'dashboards/dashboard' ) %>")

app/views/skill_requests/edit.html.erb
<div class="dashboard_container user-container">
  <% if current_user  %>
  <div id='new-skill-form'>

    <fieldset>
      <%= simple_form_for @skill_request do |f| %>
      <%= f.input :title, as: :string, placeholder:"ie: Make a doggy door" %>
      <%= f.label "Categories" %>
      <%= f.input_field :category_ids, style:"width:100%", class: 'select2 categories ajax', placeholder:"Select up to 3 Categories", data: { source: categories_path,initSelection: @skill_request.categories.map{|category|{id: category.id, text: category.name}}},value:' ' %>
      <%= f.simple_fields_for :location do |c| %>
        <%= c.input :city, label: "City", placeholder:"Select City"%>
        <%= c.input :state, label: "State", placeholder:"Select State"%>
        <%= c.input :zip, label: "Zip", placeholder:"Select Zip"%>
      <% end %>
      <%= f.input :subtitle, placeholder:"ie: Making an exterior doggy door from start to finish." %>
      <%= f.input :full_description, placeholder:"\n500 Characters Max. You can discuss further later. \n\nie: I will show you what type of door you need, the tools needed, and how to install it.This includes going to your residence and measuring the door, helping at the store and picking out the correct size doggy door and door and finally installing it. I will help you purchase the correct tools or you can use mine. The only thing I ask for you to purchase for the tools is the saw blade if needed." ,maxlength:500%>
      <%= f.submit %>
      <%end%>
      <%= link_to skill_request_path(@skill_request), method: :delete do  %>
        Delete Skill
      <% end %>
    </fieldset>
  </div>

  <div class='form-description raised-box-content'>
    <div class='content'>
    <h4 class='subject'>Almost there!</h4>

    <p class='description'>Fill out the form and we'll post it to the request skills page as well as notify anyone who has similar skills in your surrounding area to see if they can help.</p>
  </div>
  </div>
  <% else %>
  <%= render 'refills/sign_up_in_post_request' %>
  <% end %>
</div>

app/views/skill_requests/index.html.erb
<fieldset id='skill-search-box'>
    <h4 id="inner-logo-text" class="left"> Skill Climb </h4>
    <h4 id="inner-logo-text" class="right"> Learn & Earn </h4>
    <%= render partial: "refills/search_bar", locals: {button_text:"Search Skill Requests", is_remote:true, action: "/skill_requests"} %>
    <!--<%= button_to "Teach a skill", new_skill_path, method: :get %>-->
    <!--<%= button_to "Request a new skill to learn", new_skill_request_path, method: :get %>-->
</fieldset>
<div class="dashboard_container cards-container">
  <ul class="in-container">
    <li class="left"><%= button_to "Teach a skill", new_skill_path, method: :get %></li>
    <li class="left"><%= button_to "Request a new skill to learn", new_skill_request_path, method: :get %></li>
  </ul>
  <%= render "refills/cards" %>
</div>

app/views/skill_requests/new.html.erb
<div class="dashboard_container user-container">
  <% if current_user  %>
  <div class='form-description raised-box-content'>
    <div class='content'>
      <h4 class='subject'>Almost there!</h4>
      <p class='description'>Fill out the form and we'll post it to the <%= link_to 'Requested Skills', skill_requests_path %> page</p>
      <p class='description'>We'll also notify anyone who has similar skills in your surrounding area to see if they can help.</p>
    </div>
  </div>
  <div id='new-skill-form'>
    <fieldset>
     <%= simple_form_for @skill_request do |f| %>
    <ul class="accordion-tabs-minimal">
  <li class="tab-header-and-content">
    <a href="#" class="tab-link">Basic Information</a>
    <div class="tab-content">
      <p> Give general information about this skill.</p>
      <p>This should help others decide if what you are offering is what they need help with.</p>
      <%= f.input :title, as: :string, placeholder:"Enter a Title", label: false, maxlength: 35 %>
      <%= f.input :subtitle, placeholder:"Enter a Subtitle" ,label: false,
       maxlength: 45 %>
      <%= f.input :full_description, placeholder:"Enter a longer full description.\n500 Characters Max. You can discuss further later. \n\nie: I will show you what type of door you need, the tools needed, and how to install it.This includes going to your residence and measuring the door, helping at the store and picking out the correct size doggy door and door and finally installing it. I will help you purchase the correct tools or you can use mine. The only thing I ask for you to purchase for the tools is the saw blade if needed." ,maxlength:500, label:false%>
      <%= f.input :skill_level_id, label: "Your skill level", as: :select, collection: SkillLevel.all, value_method: :id %>
    </div>
  </li>
  <li class="tab-header-and-content">
    <a href="#" class="tab-link">Location, Date, & Categories</a>
    <div class="tab-content">
      <p> Add a location where you would like to learn this skill and tagit with some categories.</p>
      <%= f.input_field :category_ids, style:"width:100%", class: 'select2 categories ajax', placeholder:"Select up to 3 Categories", data: { source: categories_path }, value: '' %>
      <%= f.input :meeting_date_requested, :as => :datetime_picker, placeholder: "Choose a date of when you would like to learn this skill.", label: false %>
      <%= f.simple_fields_for :location do |c| %>
        <input id="autocomplete" placeholder="Enter the address where you would like to learn this skill"
             onFocus="geolocate()" type="text"></input>
        <%= c.hidden_field :city, label: "City", placeholder:"Select City", class: 'locality',:readonly => true %>
        <%= c.hidden_field :state, label: "State", placeholder:"Select State", class: 'administrative_area_level_1',:readonly => true %>
        <%= c.hidden_field :zip, placeholder:"Select Zip", class: 'postal_code', :readonly => true%>
      <% end %>
    </div>
  </li>
  <li class="tab-header-and-content">
    <a href="#" class="tab-link">3.) Submit</a>
    <div class="tab-content">
      <p>If you're ready to submit click the submit button. There's a preview below of what this will look like to others.</p>
      <%= f.submit %>
    </div>
  </li>
</ul>
  <%end%>
</fieldset>
  <% else %>
  <%= render 'refills/sign_up_in_post_request' %>
  <% end %>
</div>

app/views/skill_requests/skill-request-confirm-error.js.erb
$("#skill-id-<%=skill_request.id%>-button").replaceWith("<p style='color:red'>Sorry This has already been accepted by another user</p>")

app/views/skill_requests/update_dashboard.js.erb
$(".dashboard").replaceWith("<%= escape_javascript(render :partial => 'dashboards/dashboard' ) %>")

setTabs();