config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations', passwords: 'users/passwords' }

  root 'static_pages#home'

  get 'what_is/'  => 'static_pages#what_is'
  get 'faq/'      => 'static_pages#faq'
  get 'contact/'  => 'contacts#new'
  get 'coming_soon/'  => 'static_pages#coming_soon'
  get 'creating_skills_help/'  => 'static_pages#creating_skills_help'

  get 'dashboard/' => 'dashboards#show'

  resources "contacts", only: [:new, :create]

  resources :skills do
    resources :comments
    collection do
      resources :apprenticeships do
        resources :comments

      end
      get 'teaching'
      get 'learning'
      get 'archived'
    end
  end

  resources :paths do

  end

  resources :users do
    collection do
      get 'teaching'
      get 'learning'
    end
  end
  resources :skill_requests do
  end
  resources :confirmations, on: [:apprenticeships,:skill_requests], as: 'accept_date', only:[:new, :update, :delete, :create]
  resources :categories
  resources :locations
  resources :notifications

end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  include DashboardHelper
  before_filter :login_required
  def show
    current_user_dash_items
  end

end

app/helpers/dashboard_helper.rb
module DashboardHelper


  def timeline
    @sym_dates = {}
    new_dates = DateTime.now.beginning_of_day.step(DateTime.now.beginning_of_day + 17.days).select{|d| d}
    new_dates.each{|date| @sym_dates[date.to_date.to_s.to_sym] = [] }
    current_user.confirmed_upcoming_events.each do |event|
     @sym_dates.keys.each do |date|
       if event.meeting_date_scheduled.to_date.to_s == date.to_s
         @sym_dates[date] << event
       end
     end
   end
   @sym_dates
  end

  def current_user_dash_items
    @apprenticeships       = current_user.apprenticeships.includes(:skill,:location)
    @paths                 = current_user.paths
    @earning_skills        = current_user.created_skills.archived(false).includes(:categories,:creator)
    @archived_skills       = current_user.created_skills.archived(true)
    @apprentice_requests   = current_user.apprentice_requests.includes(:skill,:location,:user)
    @upcoming_events       = current_user.confirmed_upcoming_events
    @skill_requests        = current_user.skill_requests.where(has_apprenticeship: false)
    @notifications         = current_user.notifications.includes(:notifiable).sort_by{|x| x.created_at}.reverse
    @open_requests         = @earning_skills.map(&:categories).flatten.map{|x| x.skill_requests.includes(:user)}.flatten.select{|x| x.created_at > Time.now - 3.days && x.accepted_status != "confirmed" && x.user != current_user }
  end

  def item_title_link(object)
    truncate(yield(object), length:20, seperator: ".")
  end

  def dash_item_categories(categories)
    categories.limit(3).map{|category| category.name}.join(",").to_s
  end

end

app/views/dashboards/sidebar_items/_archived.html.erb
<div id="archived">
  <h6 class="title">
    <i class="toggle-info fa fa-chevron-circle-up"></i>Archived Skills
  </h6>
  <ul class="toggle-content">
    <% @archived_skills.each do |skill| %>
      <li>
        <h6>
          <%    path = skill_path(skill)
                edit_path = edit_skill_path(skill) %>
          <%=link_to item_title_link(skill) {|s| s.title}, skill_path(skill) %>
          <%= link_to edit_path do %>
            <i class="fa fa-gear"></i>
          <% end %>
        </h6>
        <h6 class="category">
          <%= dash_item_categories(skill.categories) %>
        </h6>
      </li>
    <%end%>
  </ul>
</div>

app/views/dashboards/sidebar_items/_earning.html.erb
<div id="earning">
  <h6 class="title">
    <i class="toggle-info fa fa-chevron-circle-up"></i>Earning Skills
    <span class="title-action"><%= link_to new_skill_path, id:'dash-new-skill-btn' do %>
     <%= fa_icon "plus"%>
     <% end %>
    </span>
  </h6>
  <ul class="toggle-content">
    <% @earning_skills.each do |skill| %>
      <li>
        <h6>
          <% active_text = skill.is_active ? '' : '(inactive)' %>
          <%= active_text %>
          <span class='level earning'><%=skill.apprenticeships.count %></span>
          <span class='tooltip-item'>
            <%=link_to item_title_link(skill) {|s| s.title}, skill_path(skill) %>
            <div class='tooltip'><%= skill.title%><%= active_text %></div>
          </span>
          <%= link_to edit_skill_path(skill) do %>
            <i class="fa fa-gear"></i>
          <% end %>
        </h6>
        <h6 class="category">
          <%= dash_item_categories(skill.categories) %>
        </h6>
      </li>
    <%end%>
  </ul>
</div>

app/views/dashboards/sidebar_items/_learning.html.erb
<div id="learning">
  <h6 class="title">
    <i class="toggle-info fa fa-chevron-circle-up"></i> Learning Skills
    <span class="title-action"> <%= link_to skills_path, id:'dash-learning-search' do %>
      <%= fa_icon "search-plus"%>
      <% end %>
    </span>
  </h6>
  <ul class='toggle-content'>
    <% @apprenticeships.each do |apprenticeship| %>
      <li>
        <h6>
          <span class='level learning status-<%=apprenticeship.try(:accepted_status)%> tooltip-item'>
            <div class="tooltip pending">Status: <%= apprenticeship.try(:accepted_status)%></div>
          </span>
          <span class='tooltip-item'>
            <%=link_to item_title_link(apprenticeship) {|s| s.skill.title}, skill_path(apprenticeship.skill) %>
            <div class='tooltip'><%=apprenticeship.skill.title%></div>
          </span>
          <%= link_to apprenticeship_path(apprenticeship) do %>
            <i class="fa fa-gear"></i>
          <% end %>
        </h6>
        <h6 class="category">
          <%= dash_item_categories(apprenticeship.skill.categories) %>
        </h6>
      </li>
    <%end%>
  </ul>
</div>

app/views/dashboards/sidebar_items/_paths.html.erb
<div id="paths">
  <h6 class="title">
    <i class="toggle-info fa fa-chevron-circle-up"></i> Earning Paths
  </h6>
  <ul class='toggle-content'>
    <% @paths.each do |path| %>
      <li>
        <h6>
          <span class='level paths status-<%=path.try(:accepted_status)%> tooltip-item'>
            <div class="tooltip pending">Status: <%= path.try(:accepted_status)%></div>
          </span>
          <span class='tooltip-item'>
            <%=link_to item_title_link(path) {|s| s.name}, path_path(path) %>
            <div class='tooltip'><%=path.name%></div>
          </span>
          <%= link_to path_path(path) do %>
            <i class="fa fa-gear"></i>
          <% end %>
        </h6>
        <h6 class="category">
          <%=path.skills.count%> skills in this path.
        </h6>
      </li>
    <%end%>
  </ul>
</div>

app/views/dashboards/sidebar_items/_requests.html.erb
<div id="requests">
  <h6 class="title">
    <i class="toggle-info fa fa-chevron-circle-up"></i> Wanted Skills
  </h6>
  <ul class="toggle-content">
    <% @skill_requests.each do |request| %>
      <li>
        <h6>
          <span class='status-<%=request.try(:accepted_status) %> tooltip-item'>
            <div class="tooltip pending">Status: <%= request.try(:accepted_status)%></div>
          </span>
          <%    path = skill_request_path(request)
                edit_path = edit_skill_request_path(request) %>
          <%=link_to item_title_link(request) {|s| s.try(:title) || s.try(:skill).try(:title)}, path %>
          <%= link_to edit_path do %>
            <i class="fa fa-gear"></i>
          <% end %>
        </h6>
        <h6 class="category">
          <% categories = request.try(:categories) || request.try(:skill).try(:categories) || [] %>
          <%= dash_item_categories(categories) %>
        </h6>
      </li>
    <%end%>
  </ul>
</div>