config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations', passwords: 'users/passwords' }

  root 'static_pages#home'

  get 'what_is/'  => 'static_pages#what_is'
  get 'faq/'      => 'static_pages#faq'
  get 'contact/'  => 'contacts#new'
  get 'coming_soon/'  => 'static_pages#coming_soon'
  get 'creating_skills_help/'  => 'static_pages#creating_skills_help'

  get 'dashboard/' => 'dashboards#show'

  resources "contacts", only: [:new, :create]

  resources :skills do
    resources :comments
    collection do
      resources :apprenticeships do
        resources :comments

      end
      get 'teaching'
      get 'learning'
      get 'archived'
    end
  end

  resources :paths do

  end

  resources :users do
    collection do
      get 'teaching'
      get 'learning'
    end
  end
  resources :skill_requests do
  end
  resources :confirmations, on: [:apprenticeships,:skill_requests], as: 'accept_date', only:[:new, :update, :delete, :create]
  resources :categories
  resources :locations
  resources :notifications

end

app/models/skill.rb
class Skill < ActiveRecord::Base
  include HashModifiers

  include Rails.application.routes.url_helpers

  scope :ordered_by_date,->{ order("skills.created_at DESC") }
  scope :active,         ->{ where(is_active:true)}
  scope :in_location,    ->(ids) { where('location_id in (?)',ids)}
  scope :in_categories,  ->(ids) { joins(:categories).where('categories.id in (?)', ids)}
  scope :archived,   ->(boolean) {where(archived:boolean)}

  validates :title, :subtitle, :full_description,:creator_id, :skill_level_id, :location_id, :presence => true
  validates_presence_of :categories

  before_save :add_creator_type

  belongs_to :creator, :class_name => 'User'
  belongs_to :location

  has_many :comments, :as => :commentable, dependent: :destroy

  has_many :skill_categories, dependent: :destroy
  has_many :categories, through: :skill_categories

  belongs_to  :skill_level
  belongs_to  :path

  has_many :apprenticeships, dependent: :destroy
  has_many :apprentices, through: :apprenticeships, :source => :user
  has_many :notifications, as: :notifiable
  accepts_nested_attributes_for :categories, :location, :skill_categories

  delegate :username,
           to: :creator,
           prefix: true

  delegate :city,
           :state,
           :zip,
           to: :location,
           prefix: true

  def to_param
    "#{id} #{title}".parameterize
  end

  def created_by?(user)
    user == creator
  end

  def add_creator_type
    self.creator_type = "User"
  end

  def base_uri
    skill_path(self)
  end

  def self.create_skill_from_request(skill_request_params = {})
      skill_request = skill_request_params[:skill_request]
      user = skill_request_params[:user]
      skill = self.new({
                           is_active: true,
                           title:  skill_request.title,
                           subtitle:  skill_request.subtitle,
                           full_description:  skill_request.full_description,
                           location_id:  skill_request.location_id,
                           creator_id:  user.id,
                           skill_level_id: skill_request.skill_level.id,
                           categories: skill_request.categories
                       })
      skill.save
      skill
  end

  #this send comment crap needs to change to something with a block probably
  def send_comment(user)
    self.notifications << Notification.new(item_changed: "comment", to_notify_id: self.creator.id)
  end

  def changed_comment
    {title: "Your skill just received a new comment", description: self.comments.last.content}
  end

  def self.search
    active.archived(false).includes(:location,:categories).ordered_by_date
  end

end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController

  include SearchHelper

  before_filter :login_required, only:[:new]

  def index
    @skills  = search_for(Skill,params).paginate(:page => params[:page])
    respond_to do |format|
      format.js { render :partial =>  'refills/cards', :content_type => 'text/html', layout:false }
      format.html
    end
  end

  def show
    @skill = Skill.find(params[:id])
    if !@skill.is_active? && @skill.creator != current_user
      redirect_to root_path
    end
  end

  def new
    @categories = Category.order('name')
    @skill = Skill.new
    @path  = Path.new
    @paths = current_user.paths
    @skill.categories.build
    @skill.build_location
  end

  def create
    params[:skill].merge!({creator_id: current_user.id})
    category_ids = params[:skill]["category_ids"].split(',')
    params[:skill].merge!({category_ids: category_ids})
    @skill = Skill.new(skill_params)
    @skill.location_id = find_location
    if @skill.save
      redirect_to dashboard_path
    else
      @errors = @skill.errors.full_messages
      render 'new'
    end
  end

  def edit
    skill = Skill.find(params[:id])
    if current_user == skill.creator
      @skill = skill
      @paths = current_user.paths
      @path  = skill.path || skill.build_path
    else
      redirect_to root_path
    end
  end

  def update
    params[:skill]["category_ids"] ||= ''
    @skill = Skill.find(params['id'])
    category_ids = params[:skill]["category_ids"].split(',')

    if !category_ids.empty?
      params[:skill].merge!({category_ids: category_ids})
    end
    if @skill.update_attributes(skill_params)
      if params[:skill][:location_id]
        @skill.location_id = find_location
      end
      if @skill.save
       redirect_to @skill
      else
        render 'edit'
      end
    else
      render 'edit'
    end
  end

  def apprentices
    skill        = Skill.find(params[:id])
    @apprentices = skill.apprentices
  end

  def destroy
    skill = Skill.find(params['id'])
    skill.destroy()
    redirect_to dashboard_path
  end

  private

    def skill_params
      params.require(:skill).permit(:title,:subtitle,:full_description,:price,:skill_level_id,:creator_id,:is_active,:path_id,:archived,category_ids:[],location_attributes:[:city,:state,:zip, :id])
    end

    def find_location
      params[:skill][:location_id].to_s.blank? ? Location.find_or_create_by(params[:skill][:location_attributes].symbolize_keys).id : params[:skill][:location_id]
    end


end

app/views/skills/_request_apprenticeship_form.html.erb
<%= simple_form_for Apprenticeship.new, html: {id: 'new_apprenticeship_'+new_request.to_s} do |f| %>
<%= f.hidden_field :skill_id, value: @skill.id %>
<%= f.input :request_description, input_html: {maxlength:500, placeholder:"Enter any questions or extra requests you may have for this skill. \n Max Characters: 500."}%>
<%= f.input :meeting_date_requested,readonly: true, :as => :datetime_picker,placeholder:'Click on the calendar to pick a date.', label: "When Would you Like to Meet With #{@skill.creator_username}" %>
<% location = new_request ? Location.new : @skill.location %>
<%= f.simple_fields_for location do |c| %>
<%= c.input :address, label: "Address" %>
<%= c.input :city, label: "City", value: @skill.location_city    %>
<%= c.input :state, label: "State", default: @skill.location_state %>
<%= c.input :zip, label: "Zip", html:{ value: @skill.location_zip }%>
<% end %>
 <%= f.input :skill_level_id, label: "Your skill level", as: :select, collection: SkillLevel.all, value_method: :id %>
<%= f.button :submit, value: 'Submit Request'%>
<% end %>

app/views/skills/_skill_bio.html.erb
<div class='row skill-bio'>
  <h6 class='title'>About this skill</h6>
  <p><%= simple_format(@skill.full_description) %></p>
  <% if current_user && @skill.created_by?(current_user) %>
    <p class='small-info'>You are the owner of this skill and so you cannot sign up to teach yourself. But you can edit it if you wish.<%= button_to "Edit", edit_skill_path, method: :get %></p>
  <% elsif current_user && !current_user.is_apprentice?(@skill) %>
    <button id='same-request-button'>Request Apprenticeship</button>
    <%= render "request_apprenticeship_form", new_request: false %>
    <p class='small-info'>Don't hesitate to ask for help on a similar type of project.</p>
    <p class='small-info'> ie: If someone can help teach you how trim your hedges maybe they can also mentor you on how to start a garden. You never know and it can't hurt to ask.</p>
  <% elsif current_user && current_user.is_apprentice?(@skill) %>
    <p class='small-info'> You're already enrolled in this skill. </p>
  <% else %>
    <%= button_to "Sign Up to learn this skill.", new_user_registration_path, method: :get %>
  <% end %>
</div>

app/views/skills/_skill_intro.html.erb
<div class='skill-container-transparent'>
  <div class='skill-intro'>
    <h6 class='categories'><%= @skill.categories.map{|cat| cat.name }.join(", ") %></h6>
    <div class='info'>
      <h4 id='skill-title'><%= @skill.title %>:<h6><%= @skill.subtitle %></h6>
      </h4>
      <p class='small-info'><%= "#{@skill.location_city}, #{@skill.location_state}, #{@skill.location_zip}" %></p>
      <h6>Recommended skill level: <%= @skill.skill_level.title %></h6>
      <% if @skill.respond_to?(:price) %><h6>Price: $<%= @skill.price %></h6> <% end %>
      <% if current_user && current_user.is_teacher?(@skill) %>
        <%= button_to "Edit", edit_skill_path(@skill), method: :get %>
        <%#= button_to "Manage Students", skill_users_path(skill), method:"get"%>
      <% end %>
      <% if @skill.path %>
      This skill is connected to a path. <%= link_to "Check it out", path_path(@skill.path) %>
      <% end %>
      <p>
    </div>
    <div class='profile-image'>
      <div class='skill-creator'>
        <h4>Creator: <%= @skill.creator.username %></h4>
      </div>
    </div>
  </div>
</div>

app/views/skills/edit.html.erb
<div class="dashboard_container user-container">
  <%= render "refills/skill_form" %>
   <div class='form-description raised-box-content'>
   <div class='content'>
     <% if @skill.apprenticeships.empty? %>
     <h4 class='subject'>Deleting this skill will remove it permanently.</h4>
       <%= button_to skill_path(@skill), method: :delete, class: "danger" do  %>
         Delete Skill
       <% end %>
     <%else%>
       <h4 class='subject'>You cannot delete this skill as it has apprentices. You can archive it so it doesn't display in your dashboard.</h4>
       <%= simple_form_for @skill do |f| %>
         <%= f.hidden_field :archived, value: true %>
         <%= f.submit class: "warning", value:"Archive Skill" %>
       <% end %>
     <%end%>
   </div>
  <!-- <%= render 'refills/categories' %> -->
</div>

app/views/skills/index.html.erb
<fieldset id='skill-search-box'>
  <h4 id="inner-logo-text" class="left"> Skill Climb </h4>
  <h4 id="inner-logo-text" class="right"> Learn & Earn </h4>
    <%= render partial: "refills/search_bar", locals: {button_text: "Search Skills", is_remote:true, action: '/skills'} %>
</fieldset>
<div class="dashboard_container cards-container">
  <ul class="in-container">
    <li class="left"><%= button_to "Teach a skill", new_skill_path, method: :get %></li>
    <li class="left"><%= button_to "Request a new skill to learn", new_skill_request_path, method: :get %></li>
  </ul>
<%= render "refills/cards" %>
</div>

app/views/skills/new.html.erb
<div class="dashboard_container user-container">

<div class='form-description raised-box-content'>
   <div class='content'>
   <h4 class='subject'>Awesome! You've decided to add some of your skills.</h4>
   <p class='description'>Fill out the form and you're on your way to helping others, making friendships, and earning some sweet cash.</p>
   <p class='description'>After filling out the form you should be able to see it in your dashboard in a few minutes.</p>
   <p class='description'> As soon as someone requests to learn this skill from you you'll be notified via email and on your dashboard.</p>
   <p class='description'>After the initial contact it's all up to you guys to figure it out. You can communicate from on here for the initial meetup or by email. It's up to you. Have fun!</p>
   </div>
</div>
  <%= render "refills/skill_form" %>
  <!-- <%= render 'refills/categories' %> -->
</div>

app/views/skills/show.html.erb
<%= render 'skills/skill_intro' %>
<div class='skill-container'>
  <%= render 'skills/skill_bio' %>
  <div class='comments-and-recent'>
  <div class='recent-apprentices'>
    <h6 class='title'>Recent Student Projects</h6>
    <% unless @skill.apprenticeships.empty?  %>
    <ul>
      <% @skill.apprenticeships.limit(3).each do |apprenticeship| %>
      <li>
        <h6>Requested Project</h6>
        <p><%= apprenticeship.request_description %></p>
        <h6>Completion Status</h6>
        <p><%= apprenticeship.completion_status %></p>
        <h6>Apprentice Level</h6>
        <p><%= apprenticeship.skill_level_title %></p>
      </li>
      <% end %>
  </ul>
    <% else %>
    <p> No one has enrolled in this course yet.</p>
    <% end %>
  </div>
</div>
  <div class='skill-comments'>
    <h5 class='title'>Student Reviews and Comments</h5>
    <%= render 'refills/comment' %>
  </div>
</div>

app/views/skills/teaching.html.erb
<%= render "refills/grid_items" %>
<%= render "refills/icon_bullet_points_earn" %>