config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations', passwords: 'users/passwords' }

  root 'static_pages#home'

  get 'what_is/'  => 'static_pages#what_is'
  get 'faq/'      => 'static_pages#faq'
  get 'contact/'  => 'contacts#new'
  get 'coming_soon/'  => 'static_pages#coming_soon'
  get 'creating_skills_help/'  => 'static_pages#creating_skills_help'

  get 'dashboard/' => 'dashboards#show'

  resources "contacts", only: [:new, :create]

  resources :skills do
    resources :comments
    collection do
      resources :apprenticeships do
        resources :comments

      end
      get 'teaching'
      get 'learning'
      get 'archived'
    end
  end

  resources :paths do

  end

  resources :users do
    collection do
      get 'teaching'
      get 'learning'
    end
  end
  resources :skill_requests do
  end
  resources :confirmations, on: [:apprenticeships,:skill_requests], as: 'accept_date', only:[:new, :update, :delete, :create]
  resources :categories
  resources :locations
  resources :notifications

end

app/models/skill.rb
class Skill < ActiveRecord::Base
  include HashModifiers

  include Rails.application.routes.url_helpers

  scope :ordered_by_date,->{ order("skills.created_at DESC") }
  scope :active,         ->{ where(is_active:true)}
  scope :in_location,    ->(ids) { where('location_id in (?)',ids)}
  scope :in_categories,  ->(ids) { joins(:categories).where('categories.id in (?)', ids)}
  scope :archived,   ->(boolean) {where(archived:boolean)}

  validates :title, :subtitle, :full_description,:creator_id, :skill_level_id, :location_id, :presence => true
  validates_presence_of :categories

  before_save :add_creator_type

  belongs_to :creator, :class_name => 'User'
  belongs_to :location

  has_many :comments, :as => :commentable, dependent: :destroy

  has_many :skill_categories, dependent: :destroy
  has_many :categories, through: :skill_categories

  belongs_to  :skill_level
  belongs_to  :path

  has_many :apprenticeships, dependent: :destroy
  has_many :apprentices, through: :apprenticeships, :source => :user
  has_many :notifications, as: :notifiable
  accepts_nested_attributes_for :categories, :location, :skill_categories

  delegate :username,
           to: :creator,
           prefix: true

  delegate :city,
           :state,
           :zip,
           to: :location,
           prefix: true

  def to_param
    "#{id} #{title}".parameterize
  end

  def created_by?(user)
    user == creator
  end

  def add_creator_type
    self.creator_type = "User"
  end

  def base_uri
    skill_path(self)
  end

  def self.create_skill_from_request(skill_request_params = {})
      skill_request = skill_request_params[:skill_request]
      user = skill_request_params[:user]
      skill = self.new({
                           is_active: true,
                           title:  skill_request.title,
                           subtitle:  skill_request.subtitle,
                           full_description:  skill_request.full_description,
                           location_id:  skill_request.location_id,
                           creator_id:  user.id,
                           skill_level_id: skill_request.skill_level.id,
                           categories: skill_request.categories
                       })
      skill.save
      skill
  end

  #this send comment crap needs to change to something with a block probably
  def send_comment(user)
    self.notifications << Notification.new(item_changed: "comment", to_notify_id: self.creator.id)
  end

  def changed_comment
    {title: "Your skill just received a new comment", description: self.comments.last.content}
  end

  def self.search
    active.archived(false).includes(:location,:categories).ordered_by_date
  end

end

app/views/refills/_card.html.erb
 <%= link_to skill.base_uri do %>
    <div class="hover-tile-outer">
      <div class="hover-tile-container">
        <div class="hover-tile hover-tile-visible">
          <div class='hover-tile-categories'>
            <% skill.categories.each do |cat| %>
              <p class='small-info'><%= cat.name %></p>
            <% end %>
          </div>
          <h6 class='title'><%= skill.title %></h6>
          <p class='small-info card-city'><%= skill.location_city %>,<%= skill.location_state %></p>
          <p class='subtitle'><%= skill.subtitle %></p>
        </div>
        <div class="hover-tile hover-tile-hidden">
          <p><%= truncate(skill.full_description, length: 250, separator: '.') %></p>
          <p class="text-link">Read More</p>
        </div>
      </div>
    </div>
  <% end %>

app/views/refills/_cards.html.erb
<div class="cards">
  <% if @skills.empty? %>
    <%= render "refills/no_results" %>
  <% else %>
    <%= render :partial => 'refills/card', :collection => @skills, as: :skill %>
    <%= will_paginate @skills %>
  <% end %>
</div>

app/views/refills/_comment.html.erb
<% unless @skill.comments.empty? %>
<% @skill.comments.each do |comment| %>
<div class="comment">
  <div class="comment-image">
    <img src="https://raw.github.com/Magnus-G/Random/master/placeholder_logo_2.png" alt="">
  </div>
  <div class="comment-content">
    <h6><%= comment.user.username %></h6>
    <p><%= comment.content %></p>
    <p class="comment-detail"><%= comment.created_at %></p>
  </div>
</div>
<% end %>
<% else %>
<div class='comment'>
  <p>No comments or reviews have been posted yet.</p>
</div>
<% end %>
<fieldset>
<% if current_user and @skill.apprenticeships.map(&:user).include?(current_user) %>
<%= form_for [@skill, Comment.new] do |f| %>
  <p>
    <%= f.hidden_field :user_id, value: current_user.id %>
    <%= f.hidden_field :type, value: @skill.class %>
    <%= f.label "Enter a new comment" %><br />
    <%= f.text_area :content %>
  </p>
  <p><%= f.submit "Submit" %></p>
<% end %>
<% else %>
<p> You must be currently enrolled or have taken this class to comment </p>
<% end %>
</fieldset>

app/views/refills/_footer.html.erb
   <!-- Uncomment this whole section for a sticky footer. The content of the page should be inside of this .wrapper-for-content-outside-of-footer -->
 </div>

 <footer class="footer">
  <div class="footer-logo">
    <%= image_tag("skillclimb-logo.png") %>
  </div>
  <ul>
    <!--<li><a id='about-modal' href="javascript:void(0)">About</a></li>-->
    <li><%= link_to "Contact Us", new_contact_path %></li>
    <!--<li><a id='contact-us-modal' href="javascript:void(0)">Contact Us</a></li>-->
    <!--<%#= render 'refills/contact_modal' %>-->
    <%#= render 'refills/about_modal' %>
  </ul>
    <div class="footer-secondary-links">
      <ul>
        <li><a href="javascript:void(0)">Terms and Conditions</a></li>
        <li><a href="javascript:void(0)">Privacy Policy</a></li>
      </ul>
      <ul class="footer-social">
        <li><a href="https://www.facebook.com/skillclimb">
          <img src="https://raw.githubusercontent.com/thoughtbot/refills/master/source/images/facebook-logo-circle.png" alt="Facebook">
        </a></li>
        <li><a href="https://twitter.com/SkillClimb">
          <img src="https://raw.githubusercontent.com/thoughtbot/refills/master/source/images/twitter-logo-circle.png" alt="Twitter">
        </a></li>
        <!-- <li><a href="javascript:void(0)"> -->
        <!-- <img src="https://raw.githubusercontent.com/thoughtbot/refills/master/source/images/youtube-logo-circle.png" alt="YouTube"> -->
        <!-- </a></li> -->
      </ul>
    </div>
  </footer>

app/views/refills/_icon_bullet_points.html.erb
<div class="bullets">
  <div class="bullet three-col-bullet">
    <div class="bullet-icon bullet-icon-1">
      <%= fa_icon 'graduation-cap 2x'%>
    </div>
    <div class="bullet-content">
      <h2 class='uppercase'>help others learn</h2>
      <p>We aim to create a place where people who want to learn a skill, or need help on a project, can get that help from real live people.
      <p>Not Online. Not School.</p>
      <p>In Person. Hands-On.</p>
      <p>Real Projects. Real People</p>
      </div>
  </div>
  <div class="bullet three-col-bullet">
    <div class="bullet-icon bullet-icon-2">
      <%= fa_icon 'users 2x'%>
    </div>
    <div class="bullet-content">
      <h2>FORM RELATIONSHIPS</h2>
      <p>We want people to form a relationship that fosters a great learning environment.</p>
    </div>
  </div>
  <div class="bullet three-col-bullet">
    <div class="bullet-icon bullet-icon-3">
      <%= fa_icon 'dollar 2x'%>
    </div>
    <div class="bullet-content">
      <h2>EARN CASH</h2>
      <p>Those who are offering to help others with projects or teach new skills can set an amount for what they believe their time is worth.</p>
    </div>
  </div>
</div>

app/views/refills/_icon_bullet_points_earn.html.erb
<div class="bullets earning">
  <div class="bullet three-col-bullet">
    <div class="bullet-icon bullet-icon-1">
      <%= fa_icon 'plus-square 2x'%>
      <!-- <img src="https://raw.github.com/Magnus-G/Random/master/placeholder_logo_2.png" alt=""> -->
    </div>
    <div class="bullet-content">

      <!-- <h2>This Bullet Title</h2> -->
      <h2>Add Some Skills</h2>
      <p>Whatever you're good at, or do for a hobby and want to show others post it on here!</p>
      <p>You'll be helping others and that will make you feel good. So will the extra cash for that bar tab this Saturday.</p>
      </div>
  </div>
  <div class="bullet three-col-bullet">
    <div class="bullet-icon bullet-icon-2">
      <%= fa_icon 'dot-circle-o 2x'%>
      <!-- <img src="https://raw.github.com/Magnus-G/Random/master/placeholder_logo_3.png" alt=""> -->
    </div>
    <div class="bullet-content">
      <h2>Set Your Price</h2>
      <p>Set what you think you're time is worth to teach someone that amazing skill per hour. or 1/2 hour. It's up to you. There's a few more options, but we'll ask you about those in a sec.</p>
    </div>
  </div>
  <div class="bullet three-col-bullet">
    <div class="bullet-icon bullet-icon-3">
      <%= fa_icon 'beer 2x'%>
      <!-- <img src="https://raw.github.com/Magnus-G/Random/master/placeholder_logo_4.png" alt=""> -->
    </div>
    <div class="bullet-content">
      <h2>Sit Back</h2>
      <p>Just hang out and have people contact you to teach them the things you love.</p>
    </div>
  </div>
</div>

app/views/refills/_no_results.html.erb
<div class='no-results'>
  <h5> Sorry, no results found.</h5>
  <p> Try searching a surrounding city, or different categories.</p>
  <%= image_tag("sad-panda.png") %>
</div>

app/views/refills/_notification_modal.html.erb
<div class="modal">
  <label for="modal-1">
    <%= fa_icon("exclamation-circle 3x") %>
    <h6> You have <%= modal_subjects.count %> Unseen Notifications. </h6>
  </label>
  <input class="modal-state" id="modal-1" type="checkbox" />
  <div class="modal-window">
    <div class="modal-inner">
      <label class="modal-close" for="modal-1"></label>
      <h1> Unseen Notifications </h5>
        <%= render partial: "refills/notifications", locals: { :notifications => modal_subjects} %>
    </div>
  </div>
</div>

app/views/refills/_side_image.html.erb
<div class="skill-climb-logo-text">
  <%= image_tag("skillclimb-logotext.png") %>
</div>
<% if ($is_beta && current_user && !current_user.username.include?("test_beta")) %>
<div class="beta" style="width:100%; text-align: center">
  <h1>Hey!</h1>
  <p>Thanks for signing up and checking us out.</p>
  <p>If you aren't set up for beta testing we are sorry for the inconvenience.We want to provide the best experience possible.</p>
  <p>and we are still in a beta phase for testing. We'll be up as soon as we can though.</p>
  <p>If you'd like to test us out and give some feedback send an email to me at boone.garrett@gmail.com</p>
</div>
  <% end %>
<div class="side-image example-climb">
    <div class="images-wrap"></div>
    <div class="content">
      <h4>A Simple Example</h4>
      <h1>Example of how SkillClimb works.</h1>
      <%= render "refills/grid_items_example_skill" %>
  </div>
</div>

<div class="side-image learning-and-teaching">
  <div class="content">
    <h4>Learning and Teaching</h4>
    <h1>We want people to learn new things. In person.</h1>
    <p>The main goal of SkillClimb is to allow people who have a need or a drive to learn something new to have a place where they can find others who can teach them those skills on real projects.</p>
    <p>Even if it's not necessarilly a 'skill' but a watch me then you do it. Ie: I would love to go mountain biking at every cool place in my city but don't know where the good trails are. Maybe someone on here could take you out for a day.</p>
      <p> There are tons of tutorials and how to's on youtube, or even great hands on interactive tutorials, but nothing compares to learning while doing with a person right next to them showing the best practices and correcting their mistakes before they become dangerous habits.</p>
    </div>
    <!--<div class="images-wrapper"></div>-->
  </div>
  <div class="side-image whats-on-here">
    <!--<div class="images-wrapper"></div>-->
  <div class="content">
    <h4>What Should Be on Here?</h4>
    <h1>Take on new projects. Learn new skills</h1>
    <p>We don't want people to only learn and teach things that you commonly see tutorials for on the internet like web development or how to play guitar.We want those plus anything you can think of that you'd like to learn. ie: Cooking the perfect meatballs, Laying Tile, Shooting a bow and arrow</p>
      <p> When we say anything we mean it. We'd like to see people learning small projects like <i>"Teach me to do a kickflip on a skateboard"</i> to the big ones such as <i>"My engine fell out of my car and I want someone to show me how to fix it because it happens every week.</i> We hope this is not the case, but if it is that someone will offer to help. Guitar lessons and web development definitely should be in here but we would like people to be as creative as possible of what they can show others.</p>
    </div>

  </div>

app/views/refills/_skill_form.html.erb
<div id='new-skill-form'>
  <fieldset>
    <%= simple_form_for @skill do |f| %>
    <% @errors.each do |error| %>
      <p><%= error %></p>
    <% end if @errors %>
    <%= f.input :is_active, as: :boolean, label: "Set Skill Active? " %>
    <ul class="accordion-tabs-minimal">
  <li class="tab-header-and-content">
    <a href="#" class="tab-link">1.) Basic Skill Information</a>
    <div class="tab-content">
    <p> Give general information about this skill.</p>
    <p>This should help others decide if what you are offering is what they need help with.</p>
      <div class="form-fields">
      <!--<div class="tooltip2-item">-->
        <%= f.input :title, as: :string, placeholder:"Enter a Title", label:false, maxlength: 35, input_html: { data: { tip_id: "skill_title_tip"}, class:'tooltip2-item' }%>
      <!--</div>-->
      <!--<div class="tooltip2-item">-->
        <%= f.input :subtitle,placeholder:"Enter a Subtitle", label:false, maxlength: 45,input_html: { data: { tip_id: "skill_subtitle_tip"}, class:'tooltip2-item' } %>
      <!--</div>-->
      <!--<div class="tooltip2-item">-->
        <%= f.input :skill_level_id, label: "Recommended skill level for this task", as: :select, collection: SkillLevel.all, value_method: :id,input_html: { data: { tip_id: "skill_skill_level_tip"}, class:'tooltip2-item' } %>
      <!--</div>-->
      </div>
        <div class="form-tips">
          <div class="tooltip2" id="skill_title_tip">
            <ul>
              <h6>Examples of a title</h6>
              <li>Learn Ruby</li>
              <li>Learn Fly Fishing Skills</li>
            </ul>
          </div>
          <div class="tooltip2" id="skill_subtitle_tip">
            <ul><h6>Examples of a subtitle</h6>
              <li>Beginner Ruby Development Skills</li>
              <li>Intermediate Fly Fishing techniques</li>
            </ul>
          </div>
          <div class="tooltip2" id="skill_skill_level_id_tip">
            <ul>Skill Levels:
              <% SkillLevel.all.each do |sl| %>
                <li><p class="title"><%= sl.title %></p><%= sl.description %></li>
              <% end %>
            </ul>
          </div>
        </div>
        <!--end tab content-->
  </li>
  <li class="tab-header-and-content">
    <a href="#" class="tab-link">2.) Full Description</a>
    <div class="tab-content">
            <p> Add a longer description of exactly what you will be teaching. Check out the placeholder text below for an example.</p>
            <%= f.input :full_description, placeholder:"Enter a longer full description.\n500 Characters Max. You can discuss further later. \n\nie: I will show you what type of door you need, the tools needed, and how to install it.This includes going to your residence and measuring the door, helping at the store and picking out the correct size doggy door and door and finally installing it. I will help you purchase the correct tools or you can use mine. The only thing I ask for you to purchase for the tools is the saw blade if needed." ,maxlength:500, label:false%>
    </div>
  </li>
  <li class="tab-header-and-content">
    <a href="#" class="tab-link">3.) Location And Categories</a>
    <div class="tab-content">
    <p>Specify the location where you would like to meet and complete this skill. This can be changed later per studen if you need it to change.</p>
    <%= f.simple_fields_for :location do |c| %>
      <input id="autocomplete" placeholder="Enter an address where you'd like to teach this skill"
    onFocus="geolocate()" type="text" data-geoType="address"></input>
      <%= c.hidden_field :city, label: "City", placeholder:"Select City", class: 'locality',:readonly => true %>
      <%= c.hidden_field :state, label: "State", placeholder:"Select State", class: 'administrative_area_level_1', :readonly => true %>
      <%= c.hidden_field :zip, placeholder:"Select Zip", class: 'postal_code', :readonly => true%>
    <% end %>
    <%= f.input_field :category_ids, placeholder:"Select up to 3 categories", style:"width:100%", class: 'select2 categories ajax', data: { source: categories_path, initselection: @skill.categories.map{|category| {'id' => category.id, 'text' => category.name} }}%>
    </div>

  </li>
  <li class="tab-header-and-content">
    <a href="#" class="tab-link">4.) Set price & submit. </a>
    <div class="tab-content">
    <%= f.input :path_id, label: "Add to already created path (optional)", as: :select, collection: current_user.paths, value_method: :id %>
    <%= f.input :price, label: "Set Price" %>
    <%= f.submit %>
    <%= button_to 'Create a new path', new_path_path, id:'create-new-path-button' %>
    <p> Paths are a collection of skills.</p>
    <p> Create a path with multiple skills to help others achieve a longer term goal. </p>
    <%= render '/paths/new' %>
    </div>
  </li>
</ul>
    <%= link_to "Need help creating a new skill or path?", creating_skills_help_path %>
    <br/>
    <%end%>
  </fieldset>
</div>

app/views/refills/_skill_search_container.html.erb
<div class="dashboard_container user-container">
  <fieldset id='skill-search-box'>
    <%= render "refills/search_bar" %>
  </fieldset>
<%= render "refills/cards" %>
</div>

app/views/refills/_tooltip.html.erb
<div class="tooltip-item">
  Hover for Tooltip
  <div class="tooltip">
    <p>Tooltip text</p>
  </div>
</div>

app/views/refills/_user_sign_up_side_image.html.erb
<div class="raised-box-content">
  <div class="content">
    <h4 class='subject'>Sign Up</h4>
    <h4 class='subject'>Start Earning & Learning</h4>
      <p class='description'>After signing up you'll be able to contact others
        <br />
        and start working on projects together.</p>
    </div>
</div>